[package]
name = "surreal_dive1"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
surrealdb = "2.0.2"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
