[package]
name = "document_loader"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
surrealdb = { version = "2.0.3", features = ["kv-mem", "kv-rocksdb"] }
tokio = { version = "1.40.0", features = ["full", "macros", "rt-multi-thread"] }
