[package]
name = "openai101"
version = "0.1.0"
edition = "2021"

[dependencies]
async-openai = { version = "0.24.1", features = ["native-tls-vendored"] }
dotenvy = "0.15.7"
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
